### ISSUE TITLE
Spy view

### ISSUE THREAD

**Issue by fossil22** [koraykarakus/steemnova-1.8-x#13]
Hello.Gow Theme.
Espionage report everything is written on the left side of the page. Raw materials, ships, defense, buildings. Only show numbers. I just completely reinstalled it. The problem is there immediately.

**Comment by fossil22** [comment]
Problem comes under user settings change number of espionage probes from 1 to more. Then espionage report is only displayed on the left, no information about ships, etc

**Comment by koraykarakus** [comment]
Fixed after last updates
