### ISSUE TITLE
EXPEDITIONS ISSUE

### ISSUE THREAD

**Issue by Raptor2971** [koraykarakus/steemnova-1.8-x#6]
in the event that the expedition encounters aliens or pirates and there is a battle, the fleet remains in a "block" state and does not return to the planet, you must go to the admin panel and click on "unblock" to get the battle report and the remaining fleet returning home...

**Comment by koraykarakus** [comment]
This is caused by OPBE 's not being compatible with php 8.3, issue is fixed
